### ISSUE TITLE
Move System Configs tool to separate repo

### ISSUE THREAD

**Issue by jmount1992** [qcr/tools#20]
An idea worth a discussion

Move the [System Configs](https://github.com/qcr/tools/tree/master/scripts/system_configs) portion to a separate repo. Potential advantages:

- Cleaner split between qcr tool (entry point tool to multiple things) and system configs tool
- Could make system configs tool generic, usable by anyone (currently restricted to QCR due to token embedded in scripts)
- Allow documentation about the system_configs tool to be alongside it without creating confusion between the qcr tool and system configs

I see the system configs tool as a standalone thing that could be beneficial to the wider community. But to do that, it needs to become a standalone thing.

**Comment by jmount1992** [comment]
@btalb @suddrey-qut @RSLamont I know you guys are no longer with QCR or on leave, so feel free to ignore. However, as primary developers, would love to get your thoughts on this

**Comment by btalb** [comment]
For memory, we did the first step (splitting the scripts from the actual per-robot/machine config repos).

A next logical step would be to split it to a standalone tool without the QCR specifics. Got to consider engineering burden though. The goal of this repo was to bring together "odds & ends" scripts into one place for it all to be maintained. As things spread out further, there may be more maintenance burden / plumbing together / documenting "how it all fits together".

If a motivation is use outside QCR, just remember the feature set here is relatively basic. There are [plenty of tools](https://wiki.archlinux.org/title/Dotfiles#Tools) already around in this space that offer more features but come with all the costs / challenges associated with 3rd party dependencies.

**Comment by jmount1992** [comment]
The first part we have done. The systems config tool is a separate repo, and it creates a separate repo for each system/machine. This discussion is more about simply moving scripts/systems_config to its own repo, and then doing something to how the services tool operates.

I thought the aim of this repo was to act as the entry point to various QCR tools. So QCR users only have one command to remember and can quickly see the various tools without having to search through repos or documentation. Obviously may have to go to a repo or documentation to see the purpose and how to use each tool.

Agree that there are other tools out there that might be a suitable replacement for the systems config tool. However, a small feature set is not necessarily a bad thing. Typically means easy for a newbie to understand possibilities and get started. Additionally, removing the encrypted qcrbot token and making it more generic, means students/staff could use it to track their own machines without having to have the config stored in the qcr-configs or qcr organisation.

**Comment by jmount1992** [comment]
Moved to https://github.com/qcr/system-configs
